import bpy
s = bpy.context.scene.mmr_kumopult_bac_owner.data.mmr_kumopult_bac

s.mappings.clear()
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'torso'
item_sub_1.owner = 'torso'
item_sub_1.target = '下半身'
item_sub_1.has_rotoffs = True
item_sub_1.has_loccopy = True
item_sub_1.has_ik = False
item_sub_1.offset = (1.5707963705062866, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'hips'
item_sub_1.owner = 'hips'
item_sub_1.target = '下半身'
item_sub_1.has_rotoffs = True
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (1.5707963705062866, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'chest'
item_sub_1.owner = 'chest'
item_sub_1.target = '上半身2'
item_sub_1.has_rotoffs = True
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (-1.5707963705062866, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'neck'
item_sub_1.owner = 'neck'
item_sub_1.target = '首'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'head'
item_sub_1.owner = 'head'
item_sub_1.target = '頭'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'shoulder.R'
item_sub_1.owner = 'shoulder.R'
item_sub_1.target = '肩.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'shoulder.L'
item_sub_1.owner = 'shoulder.L'
item_sub_1.target = '肩.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'upper_arm_fk.R'
item_sub_1.owner = 'upper_arm_fk.R'
item_sub_1.target = '腕.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 1.5707963705062866, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'upper_arm_fk.L'
item_sub_1.owner = 'upper_arm_fk.L'
item_sub_1.target = '腕.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 1.5707963705062866, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'forearm_fk.R'
item_sub_1.owner = 'forearm_fk.R'
item_sub_1.target = 'ひじ.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 1.5707963705062866, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'forearm_fk.L'
item_sub_1.owner = 'forearm_fk.L'
item_sub_1.target = 'ひじ.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 1.5707963705062866, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'hand_fk.L'
item_sub_1.owner = 'hand_fk.L'
item_sub_1.target = '手首.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -1.5707963705062866, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'hand_fk.R'
item_sub_1.owner = 'hand_fk.R'
item_sub_1.target = '手首.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 1.5707963705062866, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thigh_fk.R'
item_sub_1.owner = 'thigh_fk.R'
item_sub_1.target = '足.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thigh_fk.L'
item_sub_1.owner = 'thigh_fk.L'
item_sub_1.target = '足.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'shin_fk.R'
item_sub_1.owner = 'shin_fk.R'
item_sub_1.target = 'ひざ.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'shin_fk.L'
item_sub_1.owner = 'shin_fk.L'
item_sub_1.target = 'ひざ.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'foot_fk.R'
item_sub_1.owner = 'foot_fk.R'
item_sub_1.target = '足首.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'foot_fk.L'
item_sub_1.owner = 'foot_fk.L'
item_sub_1.target = '足首.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 0.0, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'toe.R'
item_sub_1.owner = 'toe.R'
item_sub_1.target = '足先EX.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, 3.1412971019744873, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'toe.L'
item_sub_1.owner = 'toe.L'
item_sub_1.target = '足先EX.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.140781879425049, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thumb.01.R'
item_sub_1.owner = 'thumb.01.R'
item_sub_1.target = '親指０.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thumb.01.L'
item_sub_1.owner = 'thumb.01.L'
item_sub_1.target = '親指０.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thumb.02.R'
item_sub_1.owner = 'thumb.02.R'
item_sub_1.target = '親指１.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thumb.02.L'
item_sub_1.owner = 'thumb.02.L'
item_sub_1.target = '親指１.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thumb.03.R'
item_sub_1.owner = 'thumb.03.R'
item_sub_1.target = '親指２.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'thumb.03.L'
item_sub_1.owner = 'thumb.03.L'
item_sub_1.target = '親指２.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_index.01.R'
item_sub_1.owner = 'f_index.01.R'
item_sub_1.target = '人指１.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_index.01.L'
item_sub_1.owner = 'f_index.01.L'
item_sub_1.target = '人指１.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_index.02.R'
item_sub_1.owner = 'f_index.02.R'
item_sub_1.target = '人指２.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_index.02.L'
item_sub_1.owner = 'f_index.02.L'
item_sub_1.target = '人指２.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_index.03.R'
item_sub_1.owner = 'f_index.03.R'
item_sub_1.target = '人指３.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_index.03.L'
item_sub_1.owner = 'f_index.03.L'
item_sub_1.target = '人指３.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_middle.01.R'
item_sub_1.owner = 'f_middle.01.R'
item_sub_1.target = '中指１.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_middle.01.L'
item_sub_1.owner = 'f_middle.01.L'
item_sub_1.target = '中指１.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_middle.02.R'
item_sub_1.owner = 'f_middle.02.R'
item_sub_1.target = '中指２.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_middle.02.L'
item_sub_1.owner = 'f_middle.02.L'
item_sub_1.target = '中指２.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_middle.03.R'
item_sub_1.owner = 'f_middle.03.R'
item_sub_1.target = '中指３.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_middle.03.L'
item_sub_1.owner = 'f_middle.03.L'
item_sub_1.target = '中指３.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_ring.01.R'
item_sub_1.owner = 'f_ring.01.R'
item_sub_1.target = '薬指１.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_ring.01.L'
item_sub_1.owner = 'f_ring.01.L'
item_sub_1.target = '薬指１.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_ring.02.R'
item_sub_1.owner = 'f_ring.02.R'
item_sub_1.target = '薬指２.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_ring.02.L'
item_sub_1.owner = 'f_ring.02.L'
item_sub_1.target = '薬指２.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_ring.03.R'
item_sub_1.owner = 'f_ring.03.R'
item_sub_1.target = '薬指３.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_ring.03.L'
item_sub_1.owner = 'f_ring.03.L'
item_sub_1.target = '薬指３.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_pinky.01.R'
item_sub_1.owner = 'f_pinky.01.R'
item_sub_1.target = '小指１.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_pinky.01.L'
item_sub_1.owner = 'f_pinky.01.L'
item_sub_1.target = '小指１.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_pinky.02.R'
item_sub_1.owner = 'f_pinky.02.R'
item_sub_1.target = '小指２.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_pinky.02.L'
item_sub_1.owner = 'f_pinky.02.L'
item_sub_1.target = '小指２.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_pinky.03.R'
item_sub_1.owner = 'f_pinky.03.R'
item_sub_1.target = '小指３.R'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
item_sub_1 = s.mappings.add()
item_sub_1.name = ''
item_sub_1.selected_owner = 'f_pinky.03.L'
item_sub_1.owner = 'f_pinky.03.L'
item_sub_1.target = '小指３.L'
item_sub_1.has_rotoffs = False
item_sub_1.has_loccopy = False
item_sub_1.has_ik = False
item_sub_1.offset = (0.0, -3.1415927410125732, 0.0)
item_sub_1.loc_axis = (True, True, True)
item_sub_1.ik_influence = 1.0
item_sub_1.selected = False
s.selected_count = 0
